services:
  database:
    image: postgres
    container_name: database
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "80:4200"